const data = {
    newFlowers: [
        {
            id: 1,
            title: "Red Tulips",
            price: 46,
            oldPrice: 60,
            image: "https://telegra.ph/file/b83978b881291a6b8765d.png",
        },
        {
            id: 2,
            title: "White roses, 7pc.",
            price: 44,
            image: "https://telegra.ph/file/350e649852e6ccf4d3ea7.png",
        },
        {
            id: 3,
            title: "Bouqueet “Dream”",
            price: 53,
            image: "https://telegra.ph/file/1329c6b988c2da2cccc1f.png",
        },
        {
            id: 4,
            title: "White lilies, 21 pc.",
            price: 70,
            image: "https://telegra.ph/file/09cd77cb2c8fb3d7513be.png",
        },
        {
            id: 5,
            title: "White lilies, 21 pc.",
            price: 70,
            image: "https://telegra.ph/file/09cd77cb2c8fb3d7513be.png",
        },
        {
            id: 6,
            title: "White lilies, 21 pc.",
            price: 70,
            image: "https://telegra.ph/file/09cd77cb2c8fb3d7513be.png",
        },
        {
            id: 7,
            title: "White lilies, 21 pc.",
            price: 70,
            image: "https://telegra.ph/file/09cd77cb2c8fb3d7513be.png",
        },
        {
            id: 8,
            title: "White lilies, 21 pc.",
            price: 70,
            image: "https://telegra.ph/file/09cd77cb2c8fb3d7513be.png",
        },
    ],
    revelantFlowers: [
        {
            id: 1,
            title: "Bouquet “Maya”",
            price: 52.5,
            image: "https://telegra.ph/file/be6784358178a3dca98f1.png",
        },
        {
            id: 2,
            title: "Red tulips, 25 pc.",
            price: 46,
            image: "https://telegra.ph/file/bbaac4c71107a937e63e3.png",
        },
        {
            id: 3,
            title: "Pink roses, 15 pc.",
            price: 34,
            image: "https://telegra.ph/file/d519221e181f84afbc2ec.png",
        },
        {
            id: 4,
            title: "Bouquet “Sunny”",
            price: 38.2,
            oldPrice: 60,
            image: "https://telegra.ph/file/94902e1eda8df90f45eda.png",
        },
        {
            id: 5,
            title: "Bouquet “Sunny”",
            price: 45,
            oldPrice: 60,
            image: "https://telegra.ph/file/94902e1eda8df90f45eda.png",
        },
        {
            id: 6,
            title: "Bouquet “Sunny”",
            price: 38.2,
            oldPrice: 60,
            image: "https://telegra.ph/file/1329c6b988c2da2cccc1f.png",
        },
        {
            id: 7,
            title: "Bouquet “Sunny”",
            price: 38.2,
            oldPrice: 60,
            image: "https://telegra.ph/file/94902e1eda8df90f45eda.png",
        },
        {
            id: 8,
            title: "Bouquet “Sunny”",
            price: 38.2,
            oldPrice: 60,
            image: "https://telegra.ph/file/94902e1eda8df90f45eda.png",
        },
    ],
    AllPlants: [
        {
            id: 1,
            title: "Lavander",
            price: 10,
            image: "https://telegra.ph/file/4ce75c55e339a37a4f119.png",
        },
        {
            id: 2,
            title: "Lavander",
            price: 10,
            image: "https://telegra.ph/file/8c14c1d37ecfddec2aac3.png",
        },
        {
            id: 3,
            title: "Red rose, 5 pc.",
            price: 16.99,
            image: "https://telegra.ph/file/4f952f51bf15f42497410.png",
        },
        {
            id: 4,
            title: "Bouquet “Spring",
            price: 20,
            oldPrice: 25,
            image: "https://telegra.ph/file/0f9be206640a33786b170.png",
        },
        {
            id: 5,
            title: "Lavander",
            price: 10,
            image: "https://telegra.ph/file/c65e8fff7c2633773e1bc.png",
        },
        {
            id: 6,
            title: "Lavander",
            price: 10,
            image: "https://telegra.ph/file/0137df65674b602372c02.png",
        },
        {
            id: 7,
            title: "Red rose, 5 pc.",
            price: 16.99,
            image: "https://telegra.ph/file/0137df65674b602372c02.png",
        },
        {
            id: 8,
            title: "Bouquet “Spring",
            price: 20,
            oldPrice: 25,
            image: "https://telegra.ph/file/0137df65674b602372c02.png",
        },
        {
            id: 9,
            title: "Bouquet “Spring",
            price: 21,
            oldPrice: 25,
            image: "https://telegra.ph/file/0137df65674b602372c02.png",
        },
        {
            id: 10,
            title: "Bouquet “Spring",
            price: 20,
            oldPrice: 25,
            image: "https://telegra.ph/file/0137df65674b602372c02.png",
        },
        {
            id: 11,
            title: "Bouquet “Spring",
            price: 20,
            oldPrice: 25,
            image: "https://telegra.ph/file/0137df65674b602372c02.png",
        },
        {
            id: 12,
            title: "Bouquet “Spring",
            price: 20,
            oldPrice: 25,
            image: "https://telegra.ph/file/0f9be206640a33786b170.png",
        },
    ],
};

export default data;
